export const systemBankOptions = [
  "ABANCA",
  "ActivoBank",
  "Avenue",
  "BBVA",
  "BNI Europa",
  "BTG Pactual",
  "Banco Atlantico Europa",
  "Banco Best",
  "Banco Bmg",
  "Banco BS2",
  "Banco C6",
  "Banco Carregosa",
  "Banco Comercial Portugues",
  "Banco CTT",
  "Banco Daycoval",
  "Banco Invest",
  "Banco Modal",
  "Banco do Brasil",
  "Banco Pan",
  "Banco Portugues de Gestao",
  "Banco Safra",
  "Banco Sofisa Direto",
  "Banco Inter",
  "Banco Original",
  "Bankinter",
  "Banrisul",
  "BPI",
  "Bradesco",
  "Caixa Economica Federal",
  "Caixa Geral de Depositos",
  "CaixaBank",
  "Cartao refeicao",
  "Cora",
  "Credito Agricola",
  "Dinheiro",
  "Edenred",
  "EuroBic",
  "Haitong Bank",
  "Itau",
  "Mercado Pago",
  "Millennium BCP",
  "Moey",
  "Montepio",
  "N26",
  "Neon",
  "Nickel",
  "Next",
  "Nomad",
  "Novo Banco",
  "Nubank",
  "Openbank",
  "PagBank",
  "Payoneer",
  "PayPal",
  "PicPay",
  "Pluxee",
  "Rico",
  "Revolut",
  "Santander",
  "Santander Brasil",
  "Sicoob",
  "Sicredi",
  "Skrill",
  "Sodexo",
  "Stone",
  "Ticket",
  "Travelex",
  "Unicambio",
  "Unicre",
  "Unibanco",
  "Wise",
  "XP",
] as const;

export type SystemBankOption = (typeof systemBankOptions)[number];

export function isSystemBankOption(value: string): value is SystemBankOption {
  return systemBankOptions.includes(value as SystemBankOption);
}

export const systemCurrencyOptions = [
  "EUR",
  "BRL",
  "USD",
  "GBP",
  "CHF",
  "CAD",
  "AUD",
] as const;

export type SystemCurrencyOption = (typeof systemCurrencyOptions)[number];

export function isSystemCurrencyOption(value: string): value is SystemCurrencyOption {
  return systemCurrencyOptions.includes(value as SystemCurrencyOption);
}
